'use client';

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useAuthUsers } from "@/features/Auth/hooks/authUsers";
import { redirect, usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Carrito Digital",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = useAuthUsers();
  const pathName = usePathname();
  
  const authRoutes = ['/login', '/register', '/forgot-password'];
  const isInAuthRoute = authRoutes.includes(pathName);
  
  if(user && isInAuthRoute) {
    return redirect('/dashboard');
  }
  



  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
