import HomeComponent from "@/components/home/HomeComponent";


export const metadata = {
    title: "Carrito Digital",
    description: "Generated by create next app",
  };

export default function Home() {
  return (
    <div >
      <HomeComponent />
    </div>
  );
}
